package tests

import (
	"context"
	"os"
	"testing"

	"github.com/rankegraph/ranke-go/internal/vectors"
	"github.com/stretchr/testify/require"
)

// The published artifact set is the spec's, not this implementation's, so running it
// here is what lets ranke-go fail conformance. Nothing else catches an encoder change:
// verification hashes stored bytes, so existing claims keep verifying while newly
// built ones quietly differ.

const (
	// testdataEnv names an already-extracted set, for working offline or against one
	// that is not published yet.
	testdataEnv = "RANKE_TESTDATA_DIR"
	// urlEnv overrides where the bundle comes from, for a fork or a staged release.
	urlEnv = "RANKE_TESTDATA_URL"
)

// expectedGenerator is the release whose published set this code is meant to match,
// bumped deliberately as the scenario references are promoted. An encoder change
// moves every id, so the set is regenerated from the new release, published, and
// named here. It is what lets a failure say WHICH of two things went wrong.
const expectedGenerator = "v0.35.0-rc.1"

// diagnose explains a failing case in terms of the set that produced it. The set is
// generated by ranke-go, so a mismatch never means this implementation disagrees with
// an outside oracle: it means the bytes moved, and the two versions say whether that
// movement is accounted for.
func diagnose(m *vectors.Manifest) string {
	if m.Provenance.Version != expectedGenerator {
		return "\nthe set was generated by " + m.Provenance.Version + " and this code expects " +
			expectedGenerator + ", so the two are out of step: regenerate and publish the set " +
			"from the newer release, then name it in expectedGenerator. Conformance is " +
			"UNCHECKED until they agree, which is not the same as passing."
	}
	return "\nthe set was generated by " + expectedGenerator + ", the release this code names, " +
		"so the encoder has moved since it was published: a conformance break rather than a " +
		"bundle waiting to catch up."
}

// artifacts resolves the set: the directory testdataEnv names, else the published
// bundle. Unreachable is a failure — silently not checking conformance is the one
// outcome worse than a red run. Fetch caches, so this costs one conditional request
// per run rather than a download.
func artifacts(t *testing.T) (string, *vectors.Manifest) {
	t.Helper()
	root := os.Getenv(testdataEnv)
	if root == "" {
		url := os.Getenv(urlEnv)
		if url == "" {
			url = vectors.LatestURL
		}
		fetched, err := vectors.Fetch(context.Background(), url, t.TempDir())
		require.NoErrorf(t, err, "fetch %s — point %s at an extracted set to work offline",
			url, testdataEnv)
		root = fetched
	}
	m, err := vectors.Load(root)
	require.NoError(t, err)
	t.Logf("artifact set from %s, generated by %s %s",
		root, m.Provenance.Generator, m.Provenance.Version)
	return root, m
}

// TestPublishedClaimVectors: every claim case must land the way the spec's manifest
// says, whichever release generated it.
func TestPublishedClaimVectors(t *testing.T) {
	root, m := artifacts(t)
	require.NotEmpty(t, m.Claims, "an artifact set with no claim cases proves nothing")

	outcomes, err := vectors.CheckClaims(context.Background(), root, m)
	require.NoError(t, err)
	for _, o := range outcomes {
		t.Run(o.File, func(t *testing.T) {
			require.Truef(t, o.Holds(), "expected verify=%v, got %v (%s) — %s%s",
				o.Expected, o.Accepted, o.Reason, o.Why, diagnose(m))
		})
	}
}

// TestPublishedContentVectors: content is addressed by the hash of its bytes, so each
// blob either answers for its hash or does not.
func TestPublishedContentVectors(t *testing.T) {
	root, m := artifacts(t)
	require.NotEmpty(t, m.Content)

	outcomes, err := vectors.CheckContent(root, m)
	require.NoError(t, err)
	for _, o := range outcomes {
		t.Run(o.File, func(t *testing.T) {
			require.Truef(t, o.Holds(), "expected verify=%v, got %v (%s) — %s%s",
				o.Expected, o.Accepted, o.Reason, o.Why, diagnose(m))
		})
	}
}

// TestPublishedBookmarkVectors: each 𝒰_hist case must land the way the manifest says.
func TestPublishedBookmarkVectors(t *testing.T) {
	root, m := artifacts(t)
	require.NotEmpty(t, m.Bookmarks, "an artifact set with no 𝒰_hist case proves nothing")

	outcomes, err := vectors.CheckBookmarks(context.Background(), root, m)
	require.NoError(t, err)
	require.Len(t, outcomes, len(m.Bookmarks))
	for _, o := range outcomes {
		t.Run(o.File, func(t *testing.T) {
			require.Truef(t, o.Holds(), "expected verify=%v, got %v (%s) — %s%s",
				o.Expected, o.Accepted, o.Reason, o.Why, diagnose(m))
		})
	}
}

// TestPublishedVectorsCoverBothOutcomes: a set of only-valid records would pass an
// implementation that accepts everything, so each keyspace needs both kinds present.
func TestPublishedVectorsCoverBothOutcomes(t *testing.T) {
	_, m := artifacts(t)

	var claimVerify, claimReject, bmVerify, bmReject int
	for _, c := range m.Claims {
		if c.Verify {
			claimVerify++
		} else {
			claimReject++
		}
	}
	for _, b := range m.Bookmarks {
		if b.Verify {
			bmVerify++
		} else {
			bmReject++
		}
	}
	require.NotZero(t, claimVerify, "no claim case must verify")
	require.NotZero(t, claimReject, "no claim case must be rejected, so accepting everything would pass")
	require.NotZero(t, bmVerify, "no bookmark case must verify")
	require.NotZero(t, bmReject, "no bookmark case must be rejected, so accepting everything would pass")
}
